extends:
- spectral:oas
- ./spectral_rules/allof-adds-property.yml
- ./spectral_rules/allof-extends-object.yml
- ./spectral_rules/allof-single-extension.yml
- ./spectral_rules/enum-value-snake-case.yml
- ./spectral_rules/query-parameter-names-camel-case.yml
- ./spectral_rules/property-of-object-type.yml
- ./spectral_rules/schema-names-pascal-case.yml
- ./spectral_rules/too-much-information.yml
rules:
  oas3-unused-component: off
  oas3-valid-schema-example: off
  tag-description: off
  oas3-api-servers: off
  openapi-tags: off
  info-description: off
