name: lint-oas

on:
  push:
    paths:
      - ./**/*.yaml
      - .github/workflows/lint-oas.yml
    branches:
      - '**'
  pull_request:
    paths:
      - ./**/*.yaml
      - .github/workflows/lint-oas.yml
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint OAS
        run: npm run oas:lint
